check empty dots in set operations on data frames
tidyverse/dplyr pull request #6036
Opened 2021-10-01 10:29 UTC by romainfrancois

closes #5891

``` r
library(dplyr, warn.conflicts = FALSE)
a <- tibble(var = 1:3)
b <- tibble(var = 2:4)
c <- tibble(var = c(1, 3, 4, 5))

intersect(a, b, c)
#> Error: `...` is not empty.
#> ℹ These dots only exist to allow future extensions and should be empty.
#> x We detected these problematic arguments:
#> • `..1`
#> ℹ Did you misspecify an argument?
setdiff(a, b, c)
#> Error: `...` is not empty.
#> ℹ These dots only exist to allow future extensions and should be empty.
#> x We detected these problematic arguments:
#> • `..1`
#> ℹ Did you misspecify an argument?
setequal(a, b, c)
#> Error: `...` is not empty.
#> ℹ These dots only exist to allow future extensions and should be empty.
#> x We detected these problematic arguments:
#> • `..1`
#> ℹ Did you misspecify an argument?
union(a, b, c)
#> Error: `...` is not empty.
#> ℹ These dots only exist to allow future extensions and should be empty.
#> x We detected these problematic arguments:
#> • `..1`
#> ℹ Did you misspecify an argument?
union_all(a, b, c)
#> Error: `...` is not empty.
#> ℹ These dots only exist to allow future extensions and should be empty.
#> x We detected these problematic arguments:
#> • `..1`
#> ℹ Did you misspecify an argument?
```

<sup>Created on 2021-10-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

2021-10-01 13:57 UTC, DavisVaughan requested changes

2021-10-01 13:57 UTC, DavisVaughan commented on R/sets.r
> +  ellipsis::check_dots_empty()
You can use the `rlang::` version now that it is in dev rlang.

We might want to consider a PR that removes all use of `ellipsis::` in favor of `rlang::`. I did that in vctrs recently. 

And we can replace any usage of `ellipsis::dots_empty` with `rlang::args_dots_empty` in the parameter docs

2021-10-01 13:57 UTC, DavisVaughan commented on R/sets.r
> +  ellipsis::check_dots_empty()
Up top we have `@param ... other arguments passed on to methods`, which we can replace with `@inheritParams rlang::args_dot_empty` since dots aren't really passed along

2021-10-01 14:23 UTC, romainfrancois commented on R/sets.r
> +  ellipsis::check_dots_empty()
Except for `union_all()` which passes them along in the default method: 

```r
#' @rdname setops
#' @export
union_all <- function(x, y, ...) UseMethod("union_all")
#' @export
union_all.default <- function(x, y, ...) vec_c(x, y, ...)
```

2021-10-01 14:27 UTC, romainfrancois commented
Thanks @DavisVaughan I'll do a follow up pr to remove the `ellipsis::`calls.

2021-10-01 14:37 UTC, DavisVaughan commented on R/sets.r
> +  ellipsis::check_dots_empty()
That seems odd. If `union_all()` is just `union()` with the addition that it doesn't remove duplicates, then I'd imagine that it should only allow 2 inputs as well.

But it allows >2 inputs, and it allow for setting vctrs `vec_c()` optional arguments:

``` r
library(dplyr)

# 3 things?
union_all(1, 2, 3)
#> [1] 1 2 3

# vs base R union()
union(1, 2, 3)
#> Error in base::union(x, y, ...): unused argument (3)

# even more confusing that you can do this
union_all(1, 2, .ptype = character())
#> Error: Can't convert <double> to <character>.
```

What if we did something like this?

```r
union_all.default <- function (x, y, ...) {
  rlang::check_dots_empty()
  vec_c(x, y)
}

# if we need the optional args
union_all.default <- function (x, y, ..., ptype = NULL, name_spec = NULL) {
  rlang::check_dots_empty()
  vec_c(x, y, .ptype = ptype, .name_spec = name_spec)
}
```

2021-10-01 14:54 UTC, romainfrancois commented on R/sets.r
> +  ellipsis::check_dots_empty()
That works for me, this probably won't cause revdep problems

2021-10-01 15:04 UTC, DavisVaughan commented on R/sets.r
> +  ellipsis::check_dots_empty()
I agree. I was also thinking keep it simple then add them later if needed

2021-10-01 15:05 UTC, DavisVaughan commented on R/sets.r
> +#' @inheritParams rlang::args_dot_empty
Did you redocument? I don't see a man file

2021-10-01 15:35 UTC, romainfrancois commented on R/sets.r
> +#' @inheritParams rlang::args_dot_empty
🤔 I'm getting `Can't find help topic 'args_dot_empty' in 'rlang' package`, using roxygen2 7.1.2

2021-10-01 15:40 UTC, DavisVaughan commented on R/sets.r
> +#' @inheritParams rlang::args_dot_empty
Missing an `s` on `dots?` i.e. `@inheritParams rlang::args_dots_empty`

2021-10-04 13:40 UTC, DavisVaughan approved these changes

2021-10-04 15:39 UTC, merged