Automatically unlist() lists of length 1 vectors
tidyverse/dplyr pull request #6368
Opened 2022-07-26 13:27 UTC by hadley

Fixes #6302

2022-07-29 19:11 UTC, DavisVaughan requested changes
I think `vec_unchop()` works better than `unlist()` here. Suggested a few tests to go along with that change, plus one that would be useful to add if you merge #6369 first

2022-07-29 19:11 UTC, DavisVaughan commented on tests/testthat/test-mutate.r
> +test_that("rowwise mutate un-lists existing length-1 list-columns", {
```suggestion
test_that("rowwise mutate un-lists existing length-1 list-columns (#6302)", {
```

2022-07-29 19:11 UTC, DavisVaughan commented on tests/testthat/test-mutate.r
> +
Some additional tests that I think are important

``` r
# Different code path from original problem
# (because `z` is based on a "new" column, `y`)
df <- tibble(x = 1:4)
df <- rowwise(df)
out <- mutate(df, y = list(1), z = y)
expect_identical(out$z, rep(1, times = 4))

# Proof that `vec_unchop()` was needed over `unlist()`
df <- tibble(x = list(tibble(a = 1), tibble(a = 2)))
df <- rowwise(df)
out <- mutate(df, y = x)
expect_identical(out$y, tibble(a = c(1, 2)))

# Preserves list-of type when evaluating symbolic column expression
df <- tibble(x = list_of(.ptype = character()))
df <- rowwise(df)
out <- mutate(df, y = x)
expect_identical(out$y, character())

# Needs #6369 too. Should be `y = NULL`, so no `y` column in result.
df <- tibble(x = list())
df <- rowwise(df)
out <- mutate(df, y = x)
expect_named(out, "x")
#> Error: Names of `out` ('x', 'y') don't match 'x'
```

2022-07-29 19:11 UTC, DavisVaughan commented on R/mutate.R
> +            result <- unlist(result, recursive = FALSE)
```suggestion
            result_ptype <- attr(result, "ptype", exact = TRUE)
            result <- vec_unchop(result, ptype = result_ptype)
```

2022-07-29 20:52 UTC, hadley commented on R/mutate.R
> +            result <- vec_unchop(result, ptype = result_ptype)
Do you think we should change the default to `ptype = attr(x, "ptype")`?

2022-08-02 16:01 UTC, DavisVaughan commented on R/mutate.R
> +            result <- vec_unchop(result, ptype = result_ptype)
I'm leaning towards no because we have tried extremely hard to keep the implementation/details of `list_of()` separated from any vctrs internals. In theory that would be admitting that `vec_unchop()` "knows" about the list-of class and I'm resistant to that without an extremely good reason to do so

2022-08-02 16:02 UTC, DavisVaughan approved these changes
LGTM. Reminder to add the test that also needs #6369 (depending on which is merged first)

2022-08-02 16:42 UTC, merged