Better handling of zero-row rowwise mutates()
tidyverse/dplyr pull request #6369
Opened 2022-07-26 14:21 UTC by hadley

Fixes #6303

2022-07-29 18:52 UTC, DavisVaughan requested changes

2022-07-29 18:52 UTC, DavisVaughan commented on src/chop.cpp
> +        }
I dont think you need this branch. I think the main point of https://github.com/tidyverse/dplyr/issues/6303#issuecomment-1159754285 was to convince us that `column` should evaluate to `list(NULL)` here rather than `list(list())` (and you automatically get `NULL` as the list element from `Rf_allocVector(VECSXP, 1)`)

2022-07-29 18:52 UTC, DavisVaughan commented on tests/testthat/test-mutate.r
> +})
Would like to see a test that ensures that `x` comes through as `NULL`. Maybe the first 2 of the 3 tests here?

If you do add a test, could the test also link to `(#6303)`?

``` r
df <- tibble(x = list())
df <- rowwise(df)

fn <- function(x) {
  stopifnot(is.null(x))
  TRUE
}

# Prove that `x` is seen as `NULL`
out <- mutate(df, y = fn(x))
expect_identical(out$y, logical())

# This ends up doing `y = NULL`, which I think is correct actually
out <- mutate(df, y = identity(x))
expect_named(out, "x")

# This one fails, but I think that is #6302 (it should also do `y = NULL`)
out <- mutate(df, y = x)
expect_named(out, "x")
#> Error: Names of `out` ('x', 'y') don't match 'x'
```

2022-07-29 20:49 UTC, hadley commented
New test for `rowwise mutate un-lists existing size-1 list-columns (#6302)` from #6368:

```R
  # Needs #6369 too. Should be `y = NULL`, so no `y` column in result.
  df <- tibble(x = list())
  df <- rowwise(df)
  out <- mutate(df, y = x)
  expect_named(out, "x")
  #> Error: Names of `out` ('x', 'y') don't match 'x'
```

2022-07-29 20:56 UTC, hadley commented on src/chop.cpp
> +        }
Oh yeah, I should have commented about that. If I remove that branch, then I get:

```R
rf <- rowwise(tibble(x = list(), y = vctrs::list_of(.ptype = character())))
mutate(rf, x2 = identity(x), y2 = identity(y))
#> # A tibble: 0 × 3
#> # Rowwise: 
#> # … with 3 variables: x <list>, y <list<chr>>, y2 <chr>
```

i.e. `x2` is absent from the output. I assume that's because it gets unpacked into `NULL` which removes the column.

2022-07-29 20:57 UTC, hadley commented on src/chop.cpp
> +        }
Oh, but based on your comment below, you think that's correct

2022-07-29 21:04 UTC, hadley commented on src/chop.cpp
> +        }
I don't have any strong feelings here; so if you think dropping the column is the correct behaviour I'm happy to go with it. I don't think it's likely to affect much code in the wild.

2022-08-02 16:20 UTC, DavisVaughan commented on src/chop.cpp
> +        }
I have a new proposal! In `tidyr::unchop()` in these cases we use `unspecified(0L)`. So we could use that here as well - that would avoid dropping the column (which does feel a little wrong) but still conveys the "unknown"ness of it.

``` r
library(tidyr)

df <- tibble(x = list())
df2 <- unchop(df, x)
df2$x
#> <unspecified> [0]

df <- tibble(x = vctrs::list_of(.ptype = integer()))
df2 <- unchop(df, x)
df2$x
#> integer(0)
```

If you wanted to keep `unspecified()` as a purely internal type here, you could also return `logical()` instead, which is the "finalized" ptype of unspecified.

``` r
library(vctrs)

unspecified()
#> <unspecified> [0]

vec_ptype_finalise(unspecified())
#> logical(0)
```

I'd be fine with either one, I think. I think both of these are better solutions than `NULL` because:
- The column isn't dropped
- They are more consistent with tidyr `unchop()`, because this is effectively an unchopping operation, as seen by the usage of `vec_unchop()` in #6368

2022-08-02 16:32 UTC, DavisVaughan commented
With the `unspecified()` or `logical()` changes, I expect these tests to pass:

```r
  df <- tibble(x = list())
  df <- rowwise(df)

  # Symbol evaluation path
  out <- mutate(df, y = x)
  expect_named(out, c("x", "y"))
  expect_identical(out$y, logical()) # or unspecified()

  # Expression evaluation path
  out <- mutate(df, y = identity(x))
  expect_named(out, c("x", "y"))
  expect_identical(out$y, logical()) # or unspecified()
```

2022-08-02 16:45 UTC, DavisVaughan commented
This PR and #6368 entangle in a fairly complex way with this example:

```r
  df <- tibble(x = list())
  df <- rowwise(df)
  out <- mutate(df, y = x)
```

When you think of both PRs together, the mutate-cols loop will start out these these two variables:

```r
result <- .data[[name]] # list()
chunks <- mask$resolve(name) # list(logical()) assuming we use logical() as the fill value here
```

The #6368 change means we then end up with:
https://github.com/tidyverse/dplyr/pull/6368/files#diff-9b0f256680edfcc73a444f94fd9d40fdc00c66105a61d2a3d03331a5938f09e8R340

```r
result <- vec_unchop(result) # NULL
```

Because we have a `NULL` `result`, we end up finalizing `result` from the `chunks` instead
https://github.com/tidyverse/dplyr/pull/6368/files#diff-9b0f256680edfcc73a444f94fd9d40fdc00c66105a61d2a3d03331a5938f09e8R380

```r
result <- chunks[[1L]] # logical()
```

This works, but I feel like it kind of works "by luck" and I'd rather `result` be correctly finalized at the `vec_unchop()` step instead. I think the problem is that the C++ code here and the `vec_unchop()` code added in #6368 need to be completely in sync for this to work exactly right.

So I think the `vec_unchop()` code in #6368 needs to set `result` to `logical()` when `identical(result, list()) && is.null(result_ptype)` is `TRUE` (rather than calling `vec_unchop()`)

2022-08-02 18:50 UTC, hadley commented
I think I've now incorporated all your suggestions. LMK if you think I've missed any cases in the test.

2022-08-02 20:16 UTC, DavisVaughan approved these changes
Looks great, thanks!

Added a few inline comments just because this one was so difficult to get right. Hopefully it (along with the tests) helps us to keep these in sync in the future

2022-08-02 20:16 UTC, DavisVaughan commented on R/mutate.R
> +              result <- logical()
```suggestion
              # i.e. `vec_ptype_finalize(unspecified())` (#6369)
              result <- logical()
```

2022-08-02 20:16 UTC, DavisVaughan commented on src/chop.cpp
> +          SET_VECTOR_ELT(column, 0, Rf_allocVector(LGLSXP, 1));
```suggestion
          // i.e. `vec_ptype_finalize(unspecified())` (#6369)
          SET_VECTOR_ELT(column, 0, Rf_allocVector(LGLSXP, 1));
```

2022-08-02 23:01 UTC, merged