Preserve type of `y` in `nest_join()`
tidyverse/dplyr pull request #6371
Opened 2022-07-26 17:19 UTC by hadley

Fixes #6295

2022-08-02 17:14 UTC, DavisVaughan requested changes

2022-08-02 17:14 UTC, DavisVaughan commented on R/join.r
> +  y_out <- set_names(y[vars$y$out], names(vars$y$out))
I think the main problem with this is that we are typically _very_ careful to only operate on bare tibbles in the join functions, since many `[` methods are broken (for our purposes). The most efficient thing to do is probably:

```r
  y_out <- set_names(y_in[vars$y$out], names(vars$y$out))
  y_out <- map(y_loc, vec_slice, x = y_out)
  y_out <- map(y_out, dplyr_reconstruct, template = y)
  new_cols[[name_var]] <- y_out
```

Then you can also add this test to ensure that attributes are retained on both `x` and `y` when they are bare data frames

```r
df1 <- data.frame(x = c(1, 2), y = c(3, 4))
df2 <- data.frame(x = c(1, 2), z = c(3, 4))

attr(df1, "foo") <- 1
attr(df2, "foo") <- 2

out <- nest_join(df1, df2, by = "x")

expect_identical(attr(out, "foo"), 1)
expect_identical(attr(out$df2[[1]], "foo"), 2)
expect_identical(attr(out$df2[[2]], "foo"), 2)
```

2022-08-02 17:14 UTC, DavisVaughan commented on R/join.r
>    # changing the key vars because of the cast
I think this comment that starts with `Currently, this regroups too often` is outdated?

With this new approach, when both `x` and `y` are grouped data frames we regroup:
- One time for `x`
- `nrow(out)` times for `y`

2022-08-02 17:14 UTC, DavisVaughan commented on tests/testthat/test-join.r
> +test_that("nest_join respects types of y",{
```suggestion
test_that("nest_join respects types of y (#6295)",{
```

2022-08-03 12:52 UTC, hadley commented on R/join.r
> +  y_out <- set_names(y[vars$y$out], names(vars$y$out))
Ah yeah, makes sense.

2022-08-03 12:52 UTC, hadley commented on R/join.r
>    # changing the key vars because of the cast
Removed the comment and moved explanation to test.

2022-08-08 20:22 UTC, DavisVaughan approved these changes

2022-08-08 20:30 UTC, merged