Check possible values of keep
tidyverse/dplyr pull request #6377
Opened 2022-07-30 13:45 UTC by hadley

Fixes #6375

2022-07-30 15:25 UTC, eutwt commented on R/join.r
> +  if (!identical(keep, TRUE) && !identical(keep, FALSE) && !identical(keep, NULL)) {
Slightly shorter with rlang functions: `!is_true(keep) && !is_false(keep) && !is_null(keep)`

2022-07-31 13:25 UTC, hadley commented on R/join.r
> +  if (!identical(keep, TRUE) && !identical(keep, FALSE) && !identical(keep, NULL)) {
Good catch, thanks!

2022-08-02 17:22 UTC, DavisVaughan requested changes

2022-08-02 17:22 UTC, DavisVaughan commented on R/join.r
> +  }
A few notes:

- `nest_join()` also uses `keep` but doesn't go through `join_mutate()`, so this check needs to be there too
- You can use `is_bool()` from rlang as another shortcut here
- Added the full stop `.` to the end of the sentence
- It probably makes sense to extract out a helper like `check_unmatched()` and `check_na_matches()`, since you have to use this check in 2 places now.

So maybe:

```r
check_keep <- function(keep, ..., error_call = caller_env()) {
  check_dots_empty0(...)
  
  if (!is_bool(keep) && !is.null(keep)) {
    abort("`keep` must be `TRUE`, `FALSE`, or `NULL`.", call = error_call)
  }
}
```

Plus maybe a `nest_join()` test

2022-08-02 20:40 UTC, hadley commented on R/join.r
> +  }
I'm not a fan of the `...` pattern for internal functions like this, so I didn't implement it. But I went with the other suggestions and generally improved the error reporting across the join family.

2022-08-02 21:05 UTC, merged