Add documentation clarifying appropriate use of weights in `slice_sample()`
tidyverse/dplyr pull request #7052
Opened 2024-07-14 18:01 UTC by apeterson91

Users may be led astray by the current language describing weighted sample for `slice_sample()`. As discussed in https://stats.stackexchange.com/q/639211/ and elaborated on in issue #6848, there's more nuance to how weights might be used for sampling. The current base R algorithm which `slice_sample()` relies on does not use the sampling weights in a way that conform to how a user might suspect the weights ought to work. 

I've added appropriate details here in the documentation including the above link for further details.

2024-07-15 08:00 UTC, etiennebacher commented
Hi, I'm not a member of the `tidyverse` team, but I just want to point out that you need to redocument the package to include this change in the `.Rd` file. You can use `devtools::document()`, or comment "/document" (without the quotes) in this PR to trigger a github action workflow (I'm not sure the latter will work).

2024-07-17 01:33 UTC, apeterson91 commented
Thanks @etiennebacher! Been a bit since I've built an R package locally appreciate the reminder.

2024-08-08 23:49 UTC, skolenik requested changes
The description of the problem is insufficient. I can poke at a more accurate answer with better references to both methodology and the existing R libraries.

(I would also point out that it is a somewhat better practice to name your branches informatively rather than `main` -- I would have called this `slice_sample_7052` to indicate the function affected and the issue number.)

2024-08-09 01:48 UTC, apeterson91 commented
I don't completely follow the first part of your comment, but your edits LGTM. 

> I would also point out that it is a somewhat better practice to name your branches informatively

Acknowledged. I'll follow this convention in the future.

2024-08-27 16:30 UTC, merged

2024-08-27 16:31 UTC, DavisVaughan commented
Thanks @apeterson91!